### ISSUE TITLE
jwt brute 异常

### ISSUE THREAD

**Issue by SkinAir** [yhy0/ChYing#2]
没添加取消模块，点两次爆破就会出两个线程，进度条也在反复横跳
![image](https://github.com/yhy0/ChYing/assets/71880910/20347ff8-4a15-4f85-b83e-155799690757)

**Comment by yhy0** [comment]
那是添加一个取消按钮来控制，还是第二次点击爆破时自动取消之前的未完成的，只运行第二次的爆破？还是两种都有？
你感觉哪种好点？

**Comment by SkinAir** [comment]
一般也不会多个jwt爆破:)，加个取消就可以了，or加个自定义爆破字典（或者加生成字典）？

**Comment by yhy0** [comment]
我都写了，添加了取消和重新爆破，自定义字典可以看看你用户目录下的`.config/ChYing` 目录,比如我的就在 `/Users/yhy/.config/ChYing` 这个目录，这个目录下会存放所有需要读取字典的配置，TWJ 模块对应的就是 `twj.txt` 字典，这个都是可以自定义的
